repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-aws-credentials
    - id: check-added-large-files
- repo: https://github.com/Yelp/detect-secrets
  rev: v0.14.3
  hooks:
    - id: detect-secrets
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
    - id: forbid-crlf
    - id: remove-crlf
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
    - id: terraform_tflint
      args:
        - '--args=--disable-rule=terraform_module_pinned_source'
